src/components/auth/Button/index.tsx, src/components/auth/Input/index.tsx, types/Auth.ts
로그인&회원가입 공통 컴포넌트 개발
- input 컴포넌트 생성
- button 컴포넌트 생성
- type 지정
#15
=>  feat: 로그인&회원가입 공통 컴포넌트 개발

src/components/auth/Button/index.tsx, src/components/auth/Button/style.ts, src/components/auth/Input/index.tsx, src/components/auth/Input/style.ts
로그인&회원가입 공통 컴포넌트 스타일링
- authInput 컴포넌트 스타일링
- authButton 컴포넌트 스타일링
#20
=> style: 로그인&회원가입 공통 컴포넌트 스타일링

src/components/common/Input/index.tsx, src/pages/SignIn/index.tsx
로그인 화면 컴포넌트 조립 및 화면 설계
- 로고 section 제작
- input 컴포넌트 조립
- login 버튼 및 회원가입 버튼 조립
#27
=> feat: 로그인 화면 설계

src/components/Post/Chat/index.tsx, src/components/Post/MessageCard/index.tsx
React import 누락으로 오류가 발생하여 해당 import 추가했습니다.
- Chat index.tsx 에 React import 추가
- MessageCard index.tsx 에 React import 추가
#36
=> fix: 채팅 컴포넌트 React import 추가

src/components/auth/Button/style.ts, src/components/common/Input/style.ts, src/pages/SignIn/style.ts
테마 변경에 맞춰 css 컬러명 수정
- Input 컴포넌트 컬러명 수정
- AuthButton 컴포넌트 컬러명 수정
- SignIn 페이지 컬러명 수정
#42
=> style: css 컬러명 수정

.eslintrc.js, package-lock.json, package.json
eslint-config-prettier 패키지 삭제
- eslint-config-prettier 패키지 삭제
#48
=> chore: eslint-config-prettier 패키지 삭제

package-lock.json, src/components/Post/Chat/index.tsx, src/components/Post/Chat/style.ts, src/components/Post/MessageCard/style.ts, src/pages/Post/index.tsx
줄 바꿈 관련 기능들을 추가하고, Post 에 채팅 컴포넌트 결합.
- Chat 의 input을 textarea로 변경.
- 채팅창에 Enter 키, Shift+Enter 키 이벤트 추가.
- MessageCard에서 여백을 구분하여 출력하도록 기능 추가.
- 빈 메세지 전송 제한 기능 추가.
- Post index에서 test 컴포넌트 자리에 채팅 컴포넌트 추가.
#39
=> feat: 채팅 컴포넌트 줄바꿈 기능 추가 및 컴포넌트 결합

src/components/common/Input/index.tsx, src/components/common/Input/style.ts, src/components/layout/style.ts, src/pages/SignIn/index.tsx, src/pages/SignIn/style.ts
더 적합한 시멘틱 요소로 수정
- Input 컴포넌트 section -> div 수정
- 로그인 화면 수정
- 라우터에 main으로 수정
#58
=> style: 시멘틱 요소 수정

src/pages/SignUp/index.tsx
회원가입 화면 레이아웃 구성
- 로고 영역
- Input 영역
- 버튼 영역
#45
=> feat: 회원가입 화면 레이아웃 구성

src/components/auth/Button/style.ts, src/pages/SignUp/index.tsx, src/pages/SignUp/style.ts
회원가입 페이지 퍼블리싱
- 회원가입 페이지 퍼블리싱
#63
=> style: 회원가입 페이지 퍼블리싱

public/monaco-themes/dark.json
=> docs : 작업용 백업 커밋

src/pages/MyPage/index.tsx, src/pages/MyPage/style.ts
마이페이지 UI 구현
- 레이아웃 구성
- 퍼블리싱
- 라디오 선택에 따른 변화 구현
#67
=> feat: 마이페이지 UI 구현

src/pages/MyPage/style.ts
마이페이지 css 속성 수정
- 안쓰는 속성 삭제
- 버튼에 cursor 속성 추가
#70
=> style: css 속성 수정

src/components/common/Input/style.ts, src/pages/MyPage/style.ts, src/pages/SignIn/style.ts, src/pages/SignUp/style.ts
width 값을 지우고 flex-grow:1로 길이가 유동적으로 채워지게 변경
그에 따른 페이지 퍼블리싱 수정
- Input 컴포넌트 스타일 수정
- 로그인 페이지 스타일 수정
- 회원가입 페이지 스타일 수정
- 마이페이지 스타일 수정
#69
=> style: Input 컴포넌트 길이 스타일 수정

package-lock.json
통일성 위해 폴더명 대소문자 수정
- component 의 Post 폴더명을 post로 수정
#76
=> rename: post 폴더명 수정

src/apis/axiosInstance.ts, src/apis/httpClient.ts, src/apis/queryClient.ts, src/main.tsx
Axios, React Query 초기 설정
- Axios 기본 설정
- React Query Client 설정
- React Query 프로젝트에 적용
- httpClient 설정
#75
=> feat: api 연결 전 초기 설정

src/apis/axiosInstance.ts, src/apis/queryClient.ts, src/hooks/Auth/useUpdateProfile.ts, src/hooks/Auth/useUserProfile.ts, src/models/Auth.ts, src/pages/MyPage/index.tsx
마이페이지 api 연결
- 회원 정보 조회 api 연결
- 프로필 이미지 수정 api 연결
- 아이디 수정 api 연결
- 닉네임 수정 api 연결
#79
=> feat: 마이페이지 api 연결

src/apis/postInstance.ts, src/components/Post/Editor/IdeEditor.tsx, src/components/Post/Header.tsx, src/models/PostHeader.type.ts, src/pages/Post/index.tsx
- IDE 웹소켓 연결 구현
- Post 페이지 Header 컴포넌트 api 연동 시도
- Post 페이지 Header 컴포넌트 타입 분리
- Post 페이지 axiosInstance 생성
- IDE 웹소켓 연결 구현
- Post 페이지 Header 컴포넌트 타입 분리
#53
=> [feat] ide websocket 통신

src/components/Post/Header.tsx, src/components/board/Header.tsx, src/components/board/UserInfo/index.tsx, src/components/board/UserInfo/style.ts, src/components/modals/AddPostModal/index.tsx, src/components/modals/AddPostModal/style.ts, src/components/modals/DeletePostModal/index.tsx, src/components/modals/DeletePostModal/style.ts, src/components/modals/EditPostModal/index.tsx, src/components/modals/EditPostModal/style.ts, src/components/modals/InvitePersonModal/index.tsx, src/components/modals/InvitePersonModal/style.ts, src/index.css, src/models/PostCard.ts, src/pages/Board/index.tsx
- 게시판 추가 모달 기능 수정
- 참여자 추가&삭제 모달 ui 및 기능 구현
- 게시글 추가,수정,삭제 모달창 ui 및 기능 구현
위와 동일
#83
=> feat / style : 남은 모달창 ui 및 기능 구현 작업

src/components/modals/AddBoardModal/style.ts, src/components/modals/AddPostModal/style.ts, src/components/modals/EditBoardModal/style.ts, src/components/modals/EditPostModal/style.ts, src/components/modals/InvitePersonModal/style.ts
- style : 모달창 placeholder 색상 변경
- style : 모달창 placeholder 색상 변경
#93
=> style : 모달창 placeholder 색상 변경

src/components/myPage/ThemeSelection/index.tsx
body에 classname을 추가해 색상 상수 선언값 변경
- body에 light classname 추가
#97
=> feat: 테마 변경 기능 구현

src/App.tsx, src/components/myPage/ThemeSelection/index.tsx, src/models/MyPage.ts, src/pages/MyPage/index.tsx
다른 페이지로 이동해도 테마 변경 유지되게 추가
- app.tsx에서 테마 상태 관리
#97
=> Feat: 다른 페이지로 이동해도 테마 변경 유지되게 추가

src/apis/Auth/authApi.ts, src/apis/axiosInstance.ts, src/components/common/Input/index.tsx, src/hooks/Auth/useSignIn.ts, src/hooks/Auth/useSignUp.ts, src/models/Auth.ts, src/models/Common.ts, src/pages/SignIn/index.tsx, src/pages/SignUp/index.tsx, vite.config.ts
로그인, 회원가입 구현
- 로그인 api 연결
- 회원가입 api 연결
#101
=> feat: auth api 연결

src/apis/Auth/myPageApi.ts, src/hooks/Auth/useUpdateProfile.ts, src/hooks/Auth/useUserProfile.ts, src/pages/MyPage/index.tsx
api 호출 함수와 react query 훅 분리
- api 호출 함수와 react query 훅 분리
#103
=> refactor: 마이페이지 api 호출 함수 분리

src/App.tsx, src/main.tsx
로그인, 회원가입 제외 페이지 접속 시 인증 여부 확인, 토큰이 없을 경우 로그인 페이지로 이동
- 토큰 여부 검사 기능 추가
- 라우터에 인증 보호 적용
#106
=> feat: 인증 보호된 라우트 적용

README.md
=> 배포를 위한 최신화

index.html, src/components/post/Editor/IdeEditor.tsx, src/models/Editor.type.ts, src/pages/Post/index.tsx, src/pages/Post/style.ts
- 웹소켓 실시간 수신 구현 시도
- 버튼 클릭 이벤트 추가
- 스타일, 타입 분리
- 웹소켓 실시간 수신 구현 시도 : 실패
- 버튼 클릭 이벤트 추가 : 클릭시 alert 출력
- 스타일, 타입 분리
#114
=> [feat] IDE 웹소켓 실시간 구현 / 그 외 기능들 구현

src/components/post/Editor/index.tsx, src/hooks/Post/useIdeWebsocket.ts
- post 컴포넌트에 token 임시 설정
- websocket 훅으로 분리
- post 컴포넌트에 token 임시 설정
- websocket 훅으로 분리
#122
=> fix : IDE websocket 수신 해결중

src/components/board/Calendar/index.tsx, src/components/board/Calendar/style.ts, src/components/board/TaskCard/index.tsx, src/components/board/TaskCard/style.ts, src/models/Calendar.ts
캘린더 컴포넌트 UI 개발 및 스타일링
- Calendar 컴포넌트 UI 개발 및 스타일링
- TaskCard 컴포넌트 UI 개발 및 스타일링
- TaskCardProps 인터페이스 지정
#126
=> feat: 캘린더 컴포넌트 UI 개발 및 스타일

package-lock.json, package.json, src/components/board/Calendar/index.tsx, src/components/board/Calendar/style.ts
react-calendar 라이브러리 설치 후 캘린더 기능 커스텀 및 스타일링
- react-calendar 라이브러리 설치
- 캘린더 기능 커스텀
- 캘린더 스타일 오버라이딩 및 UI 개선
#130
=> feat: 캘린더 기능 구현

src/apis/Ide/ideApi.ts, src/apis/Ide/useIdeWebsocket.ts, src/apis/Posts/postApi.ts, src/components/post/Editor/index.tsx, src/models/Editor.type.ts, src/models/Ide.ts, src/models/Post.ts, src/pages/Post/index.tsx
- Post 페이지 api 연동 시도 중
- IDE api 연동 시도 중
- 타입 분리
- api 훅 사용 시도중
- 마운트 관리 중
#127
=> [ feat ] Post 페이지 api 연동 시도 중, IDE api 연동 시도 중

src/hooks/Posts/useCreatePost.ts, src/hooks/Posts/usePostDetail.ts, src/hooks/Posts/usePosts.ts, src/pages/Post/index.tsx
Post 빌드 에러 해결
- 해결해서 올리고 싶었지만... 너무 오래 걸릴 것 같아서 주석처리해서 다올립니다ㅠㅠ
=> fix : Post 관련 빌드 에러 해결

src/components/login/ButtonSection/index.tsx, src/components/login/ButtonSection/style.ts, src/components/login/Header/index.tsx, src/components/login/Header/style.ts, src/pages/Login/index.tsx, src/pages/Login/style.ts
로그인 페이지 컴포넌트 분리
- LoginHeader 컴포넌트 분리
- ButtonSection 컴포넌트 분리
#138
=> feat: 로그인 페이지 컴포넌트 분리

src/apis/Auth/authApi.ts, src/hooks/Auth/useLogIn.ts, src/models/Auth.ts
로그인 Interface 이름 통일
- 로그인 Interface 이름 통일
#141
=> refactor: Interface 이름 통일

src/components/layout/sideBar/index.tsx, src/components/layout/style.ts
스타일 개선 및 라우터 추가
- 스크롤 안생기게 style 수정
- 마이페이지 연결
#150
=> feat: sideBar 개선

src/App.tsx, src/apis/Board/calenderApi.ts, src/components/board/Calendar/index.tsx, src/components/board/Calendar/style.ts, src/components/board/TaskCard/index.tsx, src/hooks/Board/useFetchScheduleList.ts, src/models/Calendar.ts
캘린더 일정 조회 api 연동
- 캘린더 일정 조회 api 연동
- 데이터 출력 확인
#145
=> feat: 캘린더 기능 api 연동

src/apis/Notifications/inviteDecisionApi.ts, src/components/modals/InvitationDecisionModal/index.tsx, src/components/myPage/Notification/index.tsx, src/hooks/Notifications/useRejectInvitation.ts, src/models/Modal.ts, src/models/MyPage.ts, src/pages/MyPage/index.tsx
boardId, boardTitle 받아오기
- 초대 결정 모달에 boardTitle 띄우기
- 초대 수락/거절 api 수정
#164
=> feat: 초대 수락/거절 수정

src/components/myPage/Notification/Item/index.tsx, src/components/myPage/Notification/Item/style.ts, src/components/myPage/Notification/style.ts
알림 아이템 스타일 획일화, 알림 스크롤 생성
- 알림 아이템 스타일 획일화
- 알림 스크롤 생성
#166
=> style: 알림 스타일 수정

src/pages/MyPage/index.tsx
마이페이지 닉네임 수정 후 data refetch 방식 변경
- useQueryClient 사용
#175
=> refactor: 닉네임 수정 후 refetch 방법 queryKey 사용으로 변경

src/pages/Board/index.tsx, src/pages/Board/style.ts
캘린더 게시판 연결
- 캘린더 게시판 연결
- 게시판 스타일링 수정
#179
=> feat: 캘린더 게시판 연결

src/App.tsx, src/components/layout/sideBar/index.tsx, src/pages/Board/index.tsx
sideBar 라우터 오류 해결
- id -> boardId로 변경
#185
=> fix: sideBar 라우터 오류 해결
